src/core/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",  include('orders_management.urls', namespace='orders_management')),
    path('account/login/', LoginView.as_view(), name='login'),
    path('account/logout/', LogoutView.as_view(), name='logout'),
]

src/orders_management/urls.py
from django.urls import path

from orders_management.views import TablePageView, DeleteTaskView

app_name = "orders_management"

urlpatterns = [
    path('', TablePageView.as_view(), name='main-page'),

    path('api/delete-task/<int:task_id>', DeleteTaskView.as_view(), name='delete-task')
]

src/orders_management/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_migrate
from django.dispatch import receiver

from orders_management.services.utils import create_employees


class Employee(AbstractUser):
    probation = models.BooleanField(default=False)
    position = models.CharField(verbose_name='Position', max_length=164, blank=True, null=True)

    class Meta:
        verbose_name = "employee"
        verbose_name_plural = "employees"


class Order(models.Model):
    task_id = models.PositiveIntegerField(unique=True, verbose_name='Task id')
    name = models.CharField(max_length=100, verbose_name='Order name')
    description = models.TextField(verbose_name="Description")
    employee = models.ForeignKey(to=Employee, on_delete=models.CASCADE, verbose_name="Empoloyee")

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return f'ID: {self.task_id} Name: {self.name}'


class TelegramUser(models.Model):
    telegram_user_id = models.IntegerField(unique=True)


@receiver(post_migrate)
def initial_employees(sender, **kwargs) -> None:
    """
    If there`re less than 3 Employee, we fill it.
    """
    employee_count = Employee.objects.count()
    if employee_count < 3:
        create_employees(Employee, employee_count)

src/orders_management/views.py
from typing import Any, Dict

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin

from orders_management.management.commands.bot import send_message_to_telegram
from orders_management.services.consumer import get_orders, delete_task


class TablePageView(LoginRequiredMixin, TemplateView):
    """
    Creating a table with user tasks.
    """

    template_name = 'orders_management/index.html'
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['tasks'] = get_orders(employee=self.request.user)
        return context


class DeleteTaskView(View):
    """
    Delete task by his primary key and sending a message using Telegram bot.
    """

    success_url = reverse_lazy('orders_management:main-page')

    def post(self, request, task_id: int):
        employee = self.request.user

        message_data = delete_task(task_id=task_id)
        send_message_to_telegram(message_data=message_data, employee=employee)
        # send_message_to_telegram(message_data=message_data, employee=employee)

        return HttpResponseRedirect(self.success_url)

src/templates/orders_management/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Producer - Consumer</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-body-tertiary">
        <form class="container-fluid justify-content-start" action="{% url 'logout'%}">
          <button class="btn btn-sm btn-outline-secondary" type="submit">Змінити аккаунт</button>
        </form>
    </nav>
    <main style="margin: 50px;">
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col" style="text-align: center; ">Замовлення</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                    <tr>
                        <td style="text-align: center;">{{task.name}}</td>
                        <td style="text-align: center; ">
                            <form action="{% url 'orders_management:delete-task' task.pk %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-danger">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                      <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"></path>
                                      <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"></path>
                                    </svg>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
</body>
</html>